name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker build . -f user-serviceAPI/dockerfile --tag ${DOCKER_USER}/user-service:latest  

      - name: Push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker push ${DOCKER_USER}/user-service:latest
